### ISSUE TITLE
用不了，卡在了this.$scope，改成不传后，就没反应了

### ISSUE THREAD

**Issue by susdevlop** [Kujiale-Mobile/Taro-Painter-Demo#9]
用不了，卡在了this.$scope，改成不传后，就没反应了
`this.ctx.draw(false, () => {    
      callback(); 
    }); `    
这里不执行

**Comment by 0JARVIS0** [comment]
抱歉，这个示例好久没更新了，刚更新了一下，应该是可以用了。
